#!/bin/bash

set -e

REPO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"
BUILD_DIR=$REPO_DIR/build
OPENSSL_PATH=$BUILD_DIR/openssl
OPENSSL_URL=https://www.openssl.org/source/old/1.1.1/openssl-1.1.1p.tar.gz

if [ ! -d $OPENSSL_PATH ]; then
    mkdir -p $OPENSSL_PATH

    echo "Downloading OpenSSL"
    OPENSSL_ARCHIVE_PATH=$OPENSSL_PATH/openssl.tar.xz
    curl -L -s -o $OPENSSL_ARCHIVE_PATH $OPENSSL_URL

    echo "Extracting OpenSSL"
    mkdir -p $OPENSSL_PATH/arm64
    tar -C $OPENSSL_PATH/arm64 -xf $OPENSSL_ARCHIVE_PATH

    mkdir -p $OPENSSL_PATH/x86_64
    tar -C $OPENSSL_PATH/x86_64 -xf $OPENSSL_ARCHIVE_PATH

    rm $OPENSSL_ARCHIVE_PATH

    echo "Building OpenSSL(arm64)"
    (cd $OPENSSL_PATH/arm64/openssl-* && \
      ./Configure darwin64-arm64-cc shared --prefix=$OPENSSL_PATH/arm64/build --openssldir=$OPENSSL_PATH/arm64/build && \
      make -j$(nproc) > /dev/null && \
      make install_sw)

    echo "Building OpenSSL(x86_64)"
    (cd $OPENSSL_PATH/x86_64/openssl-* && \
      ./Configure darwin64-x86_64-cc shared --prefix=$OPENSSL_PATH/x86_64/build --openssldir=$OPENSSL_PATH/x86_64/build && \
      make -j$(nproc) > /dev/null && \
      make install_sw)

    echo "Making fat binaries"
    # Ref https://github.com/jasonacox/Build-OpenSSL-cURL/blob/master/openssl/openssl-build-phase1.sh
    mkdir -p $OPENSSL_PATH/build/include/openssl
    cp $OPENSSL_PATH/x86_64/build/include/openssl/* $OPENSSL_PATH/build/include/openssl/
    mkdir -p $OPENSSL_PATH/build/lib
    lipo \
      "$OPENSSL_PATH/x86_64/build/lib/libcrypto.a" \
      "$OPENSSL_PATH/arm64/build/lib/libcrypto.a" \
      -create -output $OPENSSL_PATH/build/lib/libcrypto.a
    lipo \
      "$OPENSSL_PATH/x86_64/build/lib/libssl.a" \
      "$OPENSSL_PATH/arm64/build/lib/libssl.a" \
      -create -output $OPENSSL_PATH/build/lib/libssl.a
fi

set +e
