#!/bin/bash

REPO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"
source $REPO_DIR/script/bootstrap

sudo rm -rf $BUILD_DIR/bundles
mkdir -p $BUILD_DIR

xcodebuild -scheme SoftU2F install DSTROOT=$BUILD_DIR/bundles

cd $BUILD_DIR

mv ./bundles/System/Library ./bundles/Library

# The installer would fail if we included these because /System and /usr cannot
# be written to. Not sure how to prevent them from being created in the first
# place.
rm -rf ./bundles/System
rm -rf ./bundles/usr

codesign --remove-signature ./bundles/Applications/SoftU2F.app
codesign --remove-signature ./bundles/Library/Extensions/softu2f.kext

pkgbuild --analyze --root ./bundles/ SoftU2F.plist
pkgbuild --identifier com.GitHub.SoftU2F --root ./bundles/ --scripts ../install-scripts --component-plist ./SoftU2F.plist ./SoftU2F.pkg
